# http://travis-ci.org/#!/python/python
language: python
python:
    - 2.6
    - 2.7
    - 3.3
before_install:
    - pip install numpy
install:
    - python setup.py install
script:
    - python setup.py test
