language: python
python:
    - 2.6
    - 2.7
    - 3.3
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libopenblas-dev liblapack-dev libatlas-dev
    - pip install numpy
install:
    - python setup.py install
script:
    - nosetests
